name: OctaneIntegration
on:
  workflow_run:
    workflows: [GitHubActionsDemo]
    types: [requested, completed]
  pull_request:
    types: [opened, edited, closed, reopened]
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
jobs:
  octane_integration_job:
    runs-on: octane
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v1.0
        id: gitHubActionsIntegration
        with:
          octaneUrl: 'http://localhost:8080/dev'
          octaneSharedSpace: 1001
          octaneWorkspace: 3001
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          serverBaseUrl: https://github.com/TiutiuMadalin/GitHubActionsDemo
          unitTestResultsGlobPattern: "**/*.xml"
